In [62]:
import pandas as pd

In [63]:
rad = pd.read_csv('Road Accident Data.csv', delimiter=',')
wid = pd.read_csv('World Important Dates.csv', delimiter=',')

In [64]:
rad.head()

,Accident_Index,Accident Date,Day_of_Week,Junction_Control,Junction_Detail,Accident_Severity,Latitude,Light_Conditions,Local_Authority_(District),Carriageway_Hazards,...,Number_of_Casualties,Number_of_Vehicles,Police_Force,Road_Surface_Conditions,Road_Type,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200901BS70001,1/1/2021,Thursday,Give way or uncontrolled,T or staggered junction,Serious,51.512273,Daylight,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Dry,One way street,30,15:11,Urban,Fine no high winds,Car
1,200901BS70002,1/5/2021,Monday,Give way or uncontrolled,Crossroads,Serious,51.514399,Daylight,Kensington and Chelsea,None,...,11,2,Metropolitan Police,Wet or damp,Single carriageway,30,10:59,Urban,Fine no high winds,Taxi/Private hire car
2,200901BS70003,1/4/2021,Sunday,Give way or uncontrolled,T or staggered junction,Slight,51.486668,Daylight,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Dry,Single carriageway,30,14:19,Urban,Fine no high winds,Taxi/Private hire car
3,200901BS70004,1/5/2021,Monday,Auto traffic signal,T or staggered junction,Serious,51.507804,Daylight,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Frost or ice,Single carriageway,30,8:10,Urban,Other,Motorcycle over 500cc
4,200901BS70005,1/6/2021,Tuesday,Auto traffic signal,Crossroads,Serious,51.482076,Darkness - lights lit,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Dry,Single carriageway,30,17:25,Urban,Fine no high winds,Car

In [65]:
rad['Accident Date']=rad['Accident Date'].str.replace('/', '-')

In [66]:
rad['Carriageway_Hazards'].unique()

array(['None', 'Pedestrian in carriageway - not injured',
       'Other object on road',
       'Any animal in carriageway (except ridden horse)',
       'Previous accident', 'Vehicle load on road', nan], dtype=object)

In [67]:
rad['Carriageway_Hazards'] = rad['Carriageway_Hazards'].fillna('No data')
rad.head()

,Accident_Index,Accident Date,Day_of_Week,Junction_Control,Junction_Detail,Accident_Severity,Latitude,Light_Conditions,Local_Authority_(District),Carriageway_Hazards,...,Number_of_Casualties,Number_of_Vehicles,Police_Force,Road_Surface_Conditions,Road_Type,Speed_limit,Time,Urban_or_Rural_Area,Weather_Conditions,Vehicle_Type
0,200901BS70001,1-1-2021,Thursday,Give way or uncontrolled,T or staggered junction,Serious,51.512273,Daylight,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Dry,One way street,30,15:11,Urban,Fine no high winds,Car
1,200901BS70002,1-5-2021,Monday,Give way or uncontrolled,Crossroads,Serious,51.514399,Daylight,Kensington and Chelsea,None,...,11,2,Metropolitan Police,Wet or damp,Single carriageway,30,10:59,Urban,Fine no high winds,Taxi/Private hire car
2,200901BS70003,1-4-2021,Sunday,Give way or uncontrolled,T or staggered junction,Slight,51.486668,Daylight,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Dry,Single carriageway,30,14:19,Urban,Fine no high winds,Taxi/Private hire car
3,200901BS70004,1-5-2021,Monday,Auto traffic signal,T or staggered junction,Serious,51.507804,Daylight,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Frost or ice,Single carriageway,30,8:10,Urban,Other,Motorcycle over 500cc
4,200901BS70005,1-6-2021,Tuesday,Auto traffic signal,Crossroads,Serious,51.482076,Darkness - lights lit,Kensington and Chelsea,None,...,1,2,Metropolitan Police,Dry,Single carriageway,30,17:25,Urban,Fine no high winds,Car

In [68]:
wid.head()

,Sl. No,Name of Incident,Date,Month,Year,Country,Type of Event,Place Name,Impact,Affected Population,Important Person/Group Responsible,Outcome
0,1,Indus Valley Civilization Flourishes,Unknown,Unknown,2600 BC,India,Civilization,Indus Valley,Development of one of the world's earliest urb...,Local inhabitants,Indus Valley people,Positive
1,2,Battle of the Ten Kings,Unknown,Unknown,1400 BC,India,Battle,Punjab,Rigvedic tribes consolidated their control ove...,Rigvedic tribes,Sudas,Positive
2,6,Establishment of the Delhi Sultanate,Unknown,Unknown,1206,India,Political,Delhi,Muslim rule established in parts of India,People of Delhi and surrounding regions,QutbUnknownudUnknowndin Aibak,Mixed
3,7,Battle of Panipat,21,April,1526,India,Battle,Panipat,Foundation of the Mughal Empire in India,Northern Indian kingdoms,Babur,Mixed
4,8,Establishment of British Raj,1,May,1858,India,Colonial,Whole India,Start of direct British governance in India,Indian subcontinent,British East India Company/Empire,Negative

In [69]:
wid['Date'] = pd.to_numeric(wid['Date'], errors='coerce').fillna(0).astype(int)
wid['Month']=wid['Month'].str.replace('Unknown','0')

In [70]:
wid['Date'].unique()

array([   0,   21,    1,   15,    3,   11,   26,   20,   23,   10,    7,
         16,    5,   18,   25,   24,   13,    4,    9,   30,   31,    8,
          6,   22,    2,   14,   12,   28,   27,   19, 1956,   29, 1998,
       1972, 2004, 1904, 1917, 1936,   17,  509,  264])

In [71]:
wid['Month'].unique()

array(['0', 'April', 'May', 'August', 'December', 'November', 'June',
       'October', 'February', 'July', 'January', 'March', 'September'],
      dtype=object)

In [72]:
wid['Year'] = pd.to_numeric(wid['Year'].str.replace('\D',''), errors='coerce')

C:\Users\ÐŸÐ¾Ð»ÑŒÐ·Ð¾Ð²Ð°Ñ‚ÐµÐ»ÑŒ\AppData\Local\Temp\ipykernel_15328\1063830762.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  wid['Year'] = pd.to_numeric(wid['Year'].str.replace('\D',''), errors='coerce')

In [73]:
wid['Year'].unique()

array([2600, 1400, 1206, 1526, 1858, 1947, 1971, 1998, 2008, 1498, 1757,
       1857, 1905, 1960, 1984, 1999, 2005, 2012, 2022, 2020, 2018, 1951,
       1962, 1974, 1975, 1991, 2001, 2009, 2019, 1983, 2013, 2014, 2007,
       2016, 2015, 2017, 1885, 1919, 1920, 1922, 1930, 1942, 1943, 1950,
       1935, 1969, 1980, 1988, 1653, 1585, 1956, 1940, 1972, 1997, 2006,
       1986, 2010, 1990, 2004, 2002, 1948, 1945, 1977, 1987, 1978, 1931,
       1967, 1982,  105,    0,  600,  618,  960, 1271, 1644, 1842, 1850,
       1911, 1934, 1966,  150,  850, 1050,  650,  208, 1430, 1900, 1979,
       1937, 1992,  220,  755, 1290, 1420, 1530, 1949, 1958, 1989,  882,
       1237, 1380, 1490, 1598, 1730, 1917, 1938, 1941, 1918, 1921, 1929,
       1928, 1939, 1953, 1957, 1968, 1993, 2000,  538,  645,  710,  794,
       1030, 1185, 1274, 1336, 1467, 1543, 1568, 1603, 1635, 1868, 1894,
       1904, 1912, 1853, 1871, 1877, 1910, 1964, 1970, 1973, 1995, 2011,
       1788, 1803, 1851, 1854, 1901, 1915, 1902, 1932, 1838, 1835, 1891,
       1914, 1996, 1976, 1840, 1845, 1861, 1852, 1893, 1867, 1886, 1882,
       1936, 1981,  918, 1231, 1392, 1592, 1627, 1895, 1897, 1955, 1994,
       1961, 1954,  968, 1009, 1258, 1428, 1650, 1771, 1802, 1908, 1927,
       1946, 1744, 1818, 1824, 1925, 1933, 1926, 2003, 1819, 1826, 1959,
       1963, 1965, 1153, 1906, 1924, 1629, 1887, 1754, 1200,  746, 1402,
        651,  762, 1731, 1405, 1634, 1558, 1907, 1865, 1500, 1864, 1985,
       1776, 2021, 1773, 1804, 1848, 1863, 1869, 1898, 1903, 1846, 1862,
       1607, 1692, 1770, 1787, 1812, 1820, 1870, 1896, 1944, 1215, 1534,
       1588, 1642, 1660, 1707, 1760, 1801, 1805, 1832, 1837, 1859, 1666,
       1807, 1825, 1337, 1688, 1815, 2500, 1265, 1415, 1348,  732,  843,
        800, 1095, 1150, 1429, 1453, 1495, 1789, 1793, 1799,  509,  264,
        476, 1454, 1503, 1527, 1609, 1713, 1492, 1659, 1701, 1478, 1469,
       1808, 1879, 1779, 1542, 1100,  711,  940, 1000, 1397, 1349, 1362,
       1658, 1814, 1809, 1728, 1048, 1952, 1450, 1062, 1482, 1881, 1822,
       1888, 1889,  962, 1075, 1347, 1517, 1555, 1618, 1648, 1756, 1772,
       1813, 1923, 1810, 1816,  250,  750, 1325, 1521, 1821], dtype=int64)

In [74]:
rad.to_parquet('road_accident_data.parquet.gzip',compression='gzip')
wid.to_parquet('world_important_dates.parquet.gzip',compression='gzip')